apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roea

resources:
  - namespace.yaml
  - configmap.yaml
  - roead-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: roea-ai
  app.kubernetes.io/managed-by: kustomize
